.TH "SYSTEM::STARTUP::GDT" 3 "Version 0.0.01" "OSDEV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSTEM::STARTUP::GDT \- everything \fBGDT\fP related is contained in this namespace\&. this include the \fBGDT\fP entries and functions like creating it and loading it\&. the \fBGDT\fP itself is stored in the N \fBSYSTEM_INFO\fP namespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGDT_ENTRY\fP"
.br
.RI "entry inside the \fBGDT\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
everything \fBGDT\fP related is contained in this namespace\&. this include the \fBGDT\fP entries and functions like creating it and loading it\&. the \fBGDT\fP itself is stored in the N \fBSYSTEM_INFO\fP namespace\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for OSDEV from the source code\&.
