.TH "SYSTEM::STARTUP::GDT::GDT_ENTRY" 3 "Version 0.0.01" "OSDEV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSTEM::STARTUP::GDT::GDT_ENTRY \- entry inside the gdt\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <GDT\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBlimit\fP"
.br
.ti -1c
.RI "unsigned short \fBbase\fP"
.br
.ti -1c
.RI "unsigned char \fB_base\fP"
.br
.ti -1c
.RI "unsigned char \fBaccses_byte\fP"
.br
.ti -1c
.RI "unsigned char \fBlimit_flags\fP"
.br
.ti -1c
.RI "unsigned char \fB__base\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
entry inside the gdt\&. 
.PP
Definition at line \fB14\fP of file \fBGDT\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char SYSTEM::STARTUP::GDT::GDT_ENTRY::__base"

.PP
Definition at line \fB20\fP of file \fBGDT\&.h\fP\&.
.SS "unsigned char SYSTEM::STARTUP::GDT::GDT_ENTRY::_base"

.PP
Definition at line \fB17\fP of file \fBGDT\&.h\fP\&.
.SS "unsigned char SYSTEM::STARTUP::GDT::GDT_ENTRY::accses_byte"

.PP
Definition at line \fB18\fP of file \fBGDT\&.h\fP\&.
.SS "unsigned short SYSTEM::STARTUP::GDT::GDT_ENTRY::base"

.PP
Definition at line \fB16\fP of file \fBGDT\&.h\fP\&.
.SS "unsigned short SYSTEM::STARTUP::GDT::GDT_ENTRY::limit"

.PP
Definition at line \fB15\fP of file \fBGDT\&.h\fP\&.
.SS "unsigned char SYSTEM::STARTUP::GDT::GDT_ENTRY::limit_flags"

.PP
Definition at line \fB19\fP of file \fBGDT\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSDEV from the source code\&.
