.TH "SYSTEM::STARTUP::PAGING::PageMapEntry" 3 "Version 0.0.01" "OSDEV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSTEM::STARTUP::PAGING::PageMapEntry \- Represents an entry in a page map, containing information about a physical memory region\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <PAGE_MAP\&.h>\fP
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBGlobalPageMap\fP"
.br
.RI "the global page map\&. this contains information about the usage of physical pages "
.in -1c
.SH "Detailed Description"
.PP 
Represents an entry in a page map, containing information about a physical memory region\&. 
.PP
Definition at line \fB63\fP of file \fBPAGE_MAP\&.h\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBGlobalPageMap\fP\fR [friend]\fP"

.PP
the global page map\&. this contains information about the usage of physical pages 
.PP
Definition at line \fB64\fP of file \fBPAGE_MAP\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSDEV from the source code\&.
