.TH "SYSTEM::SUBSYSTEMS::CONSOLE" 3 "Version 0.0.01" "OSDEV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSTEM::SUBSYSTEMS::CONSOLE \- the console subsystem  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB__CONSOLE__STRUCTURE\fP"
.br
.ti -1c
.RI "class \fBConsole\fP"
.br
.ti -1c
.RI "struct \fBConsoleInfo\fP"
.br
.RI "contains information about the console "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBConsoleInfo\fP \fBQueryConsoleInfo\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr size_t \fBtabSize\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
the console subsystem 
.SH "Function Documentation"
.PP 
.SS "\fBConsoleInfo\fP SYSTEM::SUBSYSTEMS::CONSOLE::QueryConsoleInfo ()"

.PP
Definition at line \fB111\fP of file \fBCONSOLE\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "size_t SYSTEM::SUBSYSTEMS::CONSOLE::tabSize = 4\fR [inline]\fP, \fR [constexpr]\fP"

.PP
Definition at line \fB8\fP of file \fBCONSOLE\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OSDEV from the source code\&.
