.TH "SYSTEM::SUBSYSTEMS::RENDER::RenderState" 3 "Version 0.0.01" "OSDEV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSTEM::SUBSYSTEMS::RENDER::RenderState \- redner state class\&. a global singeton that holds the current render state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <RENDER\&.h>\fP
.SH "Detailed Description"
.PP 
redner state class\&. a global singeton that holds the current render state\&. 
.PP
Definition at line \fB70\fP of file \fBRENDER\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSDEV from the source code\&.
