.TH "SYSTEM::SUBSYSTEMS::CONSOLE::ConsoleInfo" 3 "Version 0.0.01" "OSDEV" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYSTEM::SUBSYSTEMS::CONSOLE::ConsoleInfo \- contains information about the console  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <CONSOLE\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBbuffer\fP"
.br
.ti -1c
.RI "size_t \fBcollums\fP"
.br
.ti -1c
.RI "size_t \fBrows\fP"
.br
.ti -1c
.RI "bool \fBscrollingEnabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains information about the console 
.PP
Definition at line \fB12\fP of file \fBCONSOLE\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "size_t SYSTEM::SUBSYSTEMS::CONSOLE::ConsoleInfo::buffer"

.PP
Definition at line \fB16\fP of file \fBCONSOLE\&.h\fP\&.
.SS "size_t SYSTEM::SUBSYSTEMS::CONSOLE::ConsoleInfo::collums"

.PP
Definition at line \fB17\fP of file \fBCONSOLE\&.h\fP\&.
.SS "size_t SYSTEM::SUBSYSTEMS::CONSOLE::ConsoleInfo::rows"

.PP
Definition at line \fB18\fP of file \fBCONSOLE\&.h\fP\&.
.SS "bool SYSTEM::SUBSYSTEMS::CONSOLE::ConsoleInfo::scrollingEnabled"

.PP
Definition at line \fB19\fP of file \fBCONSOLE\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OSDEV from the source code\&.
